"""empty message

Revision ID: 2172a4ef9f0c
Revises: bb19c83c0352
Create Date: 2024-11-06 11:17:35.717815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2172a4ef9f0c'
down_revision = 'bb19c83c0352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('savings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('budget')
        batch_op.drop_column('savings')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
